/* ============================================================
   IceGames portfolio: content
   Edit this file to add/change projects, testimonials, clients
   or any PT/EN string. No logic lives here.
   ============================================================ */
window.IG_DATA = {

  /* Projects, in display order. category is one of:
     "Minecraft" | "Game Design" | "IA / Software"
     media[0] is the modal hero; the rest is the gallery.
     media types: file (mp4 in assets/) | youtube (yt: video id) |
                  scroll (tall screenshot, scrollable) | image (aspect: "w / h") */
  PROJECTS: [
    {
      id: "afterlands", category: "Minecraft", title: "AfterLands", label: "Minecraft / Website", year: { pt: "2023 - hoje", en: "2023 - present" },
      short: { pt: "RankUP fundido com MMORPG: 4 anos de desenvolvimento e arquitetura para 500+ jogadores simultâneos.", en: "Prison fused with an MMORPG: 4 years of development and architecture for 500+ concurrent players." },
      long: { pt: "Quatro anos de desenvolvimento contínuo em um servidor que funde RankUP com MMORPG. Atuei como game designer e arquiteto: desenhei a progressão, a economia e o ritmo das zonas, e construí a arquitetura que sustenta 500+ jogadores simultâneos sem perda de TPS. Do lado técnico, entreguei sistemas que normalmente não existem em Minecraft vanilla: animações procedurais em NPCs, cinematics com controle de câmera, blocos animados, dungeons instanciadas por grupo e uma camada de multilinguagem que atende a base inteira. Tudo com pipeline de deploy próprio, monitoramento e rollback. Também construí o site oficial do servidor, da identidade visual à loja e ao painel de contas, para que a primeira impressão do jogador fosse do mesmo nível do jogo.", en: "Four years of continuous development on a server that fuses Prison with an MMORPG. I worked as game designer and architect: I shaped progression, economy and zone pacing, and built the architecture that holds 500+ concurrent players with no TPS loss. On the technical side I shipped systems that simply don't exist in vanilla Minecraft: procedural NPC animation, camera-driven cinematics, animated blocks, per-party instanced dungeons and a localization layer serving the whole player base. All of it with its own deploy pipeline, monitoring and rollback. I also built the server's official website, from visual identity to store and account panel, so the player's first impression matched the quality of the game itself." },
      tags: ["Java", "Game Design", "Arquitetura", "DevOps", "Website"],
      link: { url: "https://www.afterlands.com", label: { pt: "Ver o site", en: "Visit website" } },
      media: [
        { type: "file", src: "assets/afterlands-cinematic.mp4" },
        { type: "scroll", src: "assets/afterlands-site.jpg", caption: { pt: "Site oficial do AfterLands · role para ver a página inteira", en: "AfterLands official website · scroll to see the full page" } },
        { type: "file", src: "assets/afterlands-circuit.mp4" },
        { type: "file", src: "assets/afterlands-bus.mp4" },
      ],
      metrics: [{ value: "500+", label: { pt: "Jogadores simultâneos", en: "Concurrent players" } }, { value: "4 anos", label: { pt: "Em desenvolvimento", en: "In development" } }, { value: "19.9", label: { pt: "TPS em pico", en: "TPS at peak" } }],
    },
    {
      id: "highschool", category: "Minecraft", title: "High School Event", label: "Minecraft / Youtuber", year: "2026",
      short: { pt: "Evento de High School para o YouTuber Savvy Soggy, com 350+ jogadores simultâneos no ar ao mesmo tempo.", en: "High School event for YouTuber Savvy Soggy, with 350+ players live at the same time." },
      long: { pt: "Evento ao vivo de High School construído para o YouTuber Savvy Soggy, com 350+ jogadores simultâneos dentro da experiência. Simulamos uma escola de verdade: aulas, turmas, intervalos, matérias com objetivos próprios e eventos disparados no ritmo da narração. Evento ao vivo não perdoa: ou aguenta a carga no minuto em que o vídeo sobe, ou não existe. Dimensionei a infraestrutura para o pico, testei com carga simulada antes do ar e mantive o servidor estável durante toda a gravação, em inglês e com o criador comandando o roteiro.", en: "A live High School event built for YouTuber Savvy Soggy, with 350+ players inside the experience at once. We simulated a real school: classes, homerooms, breaks, subjects with their own objectives and events fired in sync with the narration. A live event is unforgiving: either it holds the load the minute the video goes up, or it doesn't exist. I sized the infrastructure for the peak, load-tested it before going live, and kept the server stable through the entire shoot, in English, with the creator driving the script." },
      tags: ["Java", "Game Design", "Eventos ao vivo", "DevOps"],
      link: { url: "https://www.youtube.com/@savvysoggy", label: { pt: "Canal do Savvy Soggy", en: "Savvy Soggy's channel" } },
      media: [{ type: "youtube", yt: "sB6nSmaSO9Q" }],
      metrics: [{ value: "350+", label: { pt: "Jogadores simultâneos", en: "Concurrent players" } }, { value: "Ao vivo", label: { pt: "Evento gravado", en: "Filmed event" } }, { value: "0", label: { pt: "Quedas no ar", en: "Crashes on air" } }],
    },
    {
      id: "tabiquest", category: "Minecraft", title: "TabiQuest", year: "2026",
      short: { pt: "Servidor Cobblemon Survival RPG com campanha principal, diálogos e progressão autorais.", en: "Cobblemon Survival RPG server with an original main campaign, dialogue and progression." },
      long: { pt: "Um servidor Cobblemon que traduz a sensação dos jogos clássicos de Pokémon para uma experiência de survival RPG. Conduzi o game design do zero: campanha principal com atos e reviravoltas, sistema de diálogos ramificados, líderes e desafios com curva de dificuldade calibrada, e uma progressão que amarra exploração, captura e economia no mesmo laço. O resultado é um servidor com narrativa própria, não uma coleção de plugins.", en: "A Cobblemon server that translates the feel of the classic Pokémon games into a survival RPG. I led game design from scratch: a main campaign with acts and turning points, a branching dialogue system, leaders and challenges on a calibrated difficulty curve, and progression that ties exploration, catching and economy into one loop. The result is a server with a narrative of its own, not a pile of plugins." },
      tags: ["Game Design", "Cobblemon", "Narrativa", "Java"],
      media: [{ type: "youtube", yt: "2x2jBJeE13U" }],
      metrics: [{ value: "1", label: { pt: "Campanha autoral", en: "Original campaign" } }, { value: "RPG", label: { pt: "Survival + RPG", en: "Survival + RPG" } }, { value: "PT / EN", label: { pt: "Idiomas", en: "Languages" } }],
    },
    {
      id: "cortex", category: "IA / Software", title: "CORTEX", year: "2025",
      short: { pt: "Bot de Discord com RAG que responde jogadores e clientes automaticamente, 24 horas por dia.", en: "Discord bot with RAG that answers players and clients automatically, around the clock." },
      long: { pt: "Bot de Discord em Python (Pycord) com uma camada de IA de verdade por trás: as respostas vêm de RAG sobre um banco de dados com as informações do servidor, então o bot responde com o conteúdo real do projeto em vez de improvisar. Ele atende mensagens diretas, identifica sozinho quando uma dúvida já está no FAQ e escala para humanos quando não está. Junto vêm os sistemas que mantêm a comunidade em pé: leveling, moderação e formulários em modals.", en: "A Python (Pycord) Discord bot with a real AI layer behind it: answers come from RAG over a database of server information, so the bot replies with the project's actual content instead of improvising. It handles direct messages, recognizes on its own when a question is already covered by the FAQ, and escalates to a human when it isn't. Alongside come the systems that keep a community running: leveling, moderation and modal-based forms." },
      tags: ["Python", "Pycord", "RAG", "LLMs"],
      media: [{ type: "scroll", src: "assets/cortex-demo.png", caption: { pt: "Resposta do CORTEX no Discord, com contexto buscado via RAG", en: "CORTEX answering in Discord, with context retrieved via RAG" } }],
      metrics: [{ value: "24/7", label: { pt: "Atendimento", en: "Coverage" } }, { value: "RAG", label: { pt: "Respostas com fonte", en: "Sourced answers" } }, { value: "DM + FAQ", label: { pt: "Canais", en: "Channels" } }],
    },
    {
      id: "dinosaurs", category: "Game Design", title: "Dinosaurs: Lost Depths", label: "Game Design / Marketplace", year: "2026",
      short: { pt: "Game design completo de um addon de Marketplace para a Panda Studios, da ideação ao documento final.", en: "Full game design for a Marketplace addon for Panda Studios, from ideation to final document." },
      long: { pt: "Serviço de game design de ponta a ponta para um addon de Marketplace da Panda Studios. Parti da ideação e entreguei o documento de design final: o jogador monta uma escavadeira gigante e desce até as Profundezas Perdidas em busca de dinossauros pré-históricos, em uma premissa inspirada em Viagem ao Centro da Terra. Defini o loop de escavação e exploração, a progressão da máquina, o bestiário e a estrutura de conteúdo, tudo pronto para o time de produção executar sem adivinhação.", en: "End-to-end game design for a Panda Studios Marketplace addon. I started at ideation and delivered the final design document: the player assembles a giant drilling rig and descends into the Lost Depths hunting prehistoric dinosaurs, on a premise inspired by Journey to the Center of the Earth. I defined the digging and exploration loop, the rig progression, the bestiary and the content structure, all ready for the production team to execute without guesswork." },
      tags: ["Game Design", "GDD", "Marketplace"],
      media: [{ type: "image", aspect: "1656 / 2339", src: "assets/dinosaurs-gdd-p1.png" }],
      metrics: [{ value: "Cliente", label: { pt: "Panda Studios", en: "Panda Studios" } }, { value: "GDD", label: { pt: "Entrega final", en: "Final delivery" } }, { value: "Bedrock", label: { pt: "Plataforma", en: "Platform" } }],
    },
    {
      id: "iglanguages", category: "Minecraft", title: "IGLanguages", year: "2025",
      short: { pt: "Plugin de multilinguagem publicado no Spigot, com versão premium integrada ao Crowdin.", en: "Localization plugin published on Spigot, with a premium version integrated with Crowdin." },
      long: { pt: "Plugin publicado no Spigot que resolve um problema chato de verdade: deixar um servidor de Minecraft multilíngue sem reescrever cada mensagem na mão. Configuração direta, troca de idioma por jogador e uma versão premium integrada ao Crowdin, a maior plataforma de tradução do mundo, para que equipes traduzam o servidor de forma profissional e contínua. Produto mantido, documentado e com suporte a donos de servidor.", en: "A plugin published on Spigot that solves a genuinely tedious problem: making a Minecraft server multilingual without rewriting every message by hand. Straightforward setup, per-player language switching, and a premium version integrated with Crowdin, the world's largest translation platform, so teams can localize a server professionally and continuously. A maintained, documented product with support for server owners." },
      tags: ["Java", "Spigot", "Crowdin", "i18n"],
      link: { url: "https://www.spigotmc.org/resources/iglanguages-the-multi-language-plugin-1-8-1-21.125318/", label: { pt: "Ver na SpigotMC", en: "View on SpigotMC" } },
      media: [{ type: "scroll", src: "assets/iglanguages-demo.gif", caption: { pt: "Troca de idioma em tempo real, sem reiniciar o servidor", en: "Real-time language switching, no server restart" } }],
      metrics: [{ value: "Spigot", label: { pt: "Publicado", en: "Published" } }, { value: "Crowdin", label: { pt: "Integração premium", en: "Premium integration" } }, { value: "Multi", label: { pt: "Idiomas", en: "Languages" } }],
    },
  ],

  TESTIMONIALS: [
    { name: "Savvy Soggy", stars: "★★★★★",
      role: { pt: "YouTuber · High School Event", en: "YouTuber · High School Event" },
      quote: { pt: "I just wanted to film a school episode. He handed me an entire school, classes and bell included, and held 350 people online without dropping mid-shoot.", en: "I just wanted to film a school episode. He handed me an entire school, classes and bell included, and held 350 people online without dropping mid-shoot." } },
    { name: "Screw", stars: "★★★★★",
      role: { pt: "Fundador · TabiQuest", en: "Founder · TabiQuest" },
      quote: { pt: "I wanted the feeling of the Pokémon games I played as a kid, but inside Minecraft. It's the first time I saw someone actually get it: there's a campaign, there's dialogue, there's that moment of leaving home for the first time.", en: "I wanted the feeling of the Pokémon games I played as a kid, but inside Minecraft. It's the first time I saw someone actually get it: there's a campaign, there's dialogue, there's that moment of leaving home for the first time." } },
    { name: "Night", stars: "★★★★★",
      role: { pt: "Panda Studios · Dinosaurs: Lost Depths", en: "Panda Studios · Dinosaurs: Lost Depths" },
      quote: { pt: "Recebemos o documento e o time de produção começou a trabalhar no mesmo dia, sem aquela rodada de \"e isso aqui, como funciona?\". Para um addon de Marketplace, isso é o que decide o prazo.", en: "We got the document and the production team started working the same day, with none of that \"wait, how does this part work?\" round. For a Marketplace addon, that's what decides the deadline." } },
    { name: "Victor Polleto", stars: "★★★★★",
      role: { pt: "CEO · Mia Studios", en: "CEO · Mia Studios" },
      quote: { pt: "Nosso prazo era curto e a gente precisava do servidor de produção funcionando para ontem. Entregou antes do combinado e com mais do que a gente tinha pedido: o time entrou trabalhando no mesmo dia.", en: "Our deadline was tight and we needed the production server working yesterday. He delivered ahead of schedule and with more than we had asked for: the team started working the same day." } },
    { name: "Sarah Klein", stars: "★★★★★",
      role: { pt: "CTO · Nordic Apps", en: "CTO · Nordic Apps" },
      quote: { pt: "We were worried about the timezone and the language barrier. In the end, the process that used to eat the team's morning now runs on its own with AI, and the answers come out better than ours.", en: "We were worried about the timezone and the language barrier. In the end, the process that used to eat the team's morning now runs on its own with AI, and the answers come out better than ours." } },
  ],

  /* Logos in the hero marquee. w/h are the box the logo is fitted into. href "" = not a link */
  CLIENTS: [
    { id: "client-soggy",      name: "Soggy",         src: "assets/client-soggy.jpg",      w: "78px",  h: "78px",  href: "https://www.youtube.com/@savvysoggy" },
    { id: "client-afterlands", name: "AfterLands",    src: "assets/client-afterlands.png", w: "270px", h: "72px",  href: "https://www.afterlands.com" },
    { id: "client-tabiquest",  name: "TabiQuest",     src: "assets/client-tabiquest.png",  w: "110px", h: "110px", href: "" },
    { id: "client-mia",        name: "Mia Studios",   src: "assets/client-mia.png",        w: "212px", h: "72px",  href: "https://www.mia-studios.net" },
    { id: "client-panda",      name: "Panda Studios", src: "assets/client-panda.png",      w: "92px",  h: "84px",  href: "https://www.panda-studios.net/" },
    { id: "client-eco",        name: "Eco Studios",   src: "assets/client-eco.png",        w: "206px", h: "72px",  href: "https://www.ecostudios.com.br/" },
  ],

  /* Services: n selects STR keys serv{n}Title/Model/Promise/Desc; proof = project id opened by "See the proof" */
  SERVICES: [
    { n: 1, proof: "dinosaurs",  tags: ["Game Design", "GDD", "Narrativa"] },
    { n: 2, proof: "afterlands", tags: ["Java", "Spigot / Paper", "Redis"] },
    { n: 3, proof: "highschool", tags: ["DevOps", "Teste de carga", "Monitoramento"] },
    { n: 4, proof: "cortex",     tags: ["Java / Spring", "Python", "RAG", "Vue"] },
  ],

  /* Tag / metric words written in PT that get translated when lang === "en" */
  VOCAB_EN: {
    "Arquitetura": "Architecture",
    "Eventos ao vivo": "Live events",
    "Narrativa": "Narrative",
    "Teste de carga": "Load testing",
    "Monitoramento": "Monitoring",
    "4 anos": "4 years",
    "Ao vivo": "Live",
    "Cliente": "Client",
    "Multi": "Multi",
  },

  /* Every UI string. Keys must exist in BOTH pt and en. */
  STR: {
    pt: {
      navProjects: "Projetos", navServices: "Serviços", navProcess: "Como trabalho", navAbout: "Sobre", navContact: "Contato", navCta: "Vamos conversar",
      heroAvailable: "Disponível para novos projetos",
      heroRole: "Software Engineer & Game Designer · Certificado pela CalArts",
      heroH1a: "Transformando o impossível em ", heroH1b: "possível",
      heroClients: "Trabalhei com", heroClientFree: "+ logo",
      heroSub: "Sou Vitor Albert, também conhecido como IceGames. Desenho o jogo e construo a engenharia que o mantém de pé: servidores de Minecraft, eventos ao vivo e software com IA que rodam com centenas de jogadores ao mesmo tempo.",
      heroCta1: "Ver projetos", heroCta2: "Vamos conversar",
      statPlayers: "Jogadores impactados", statProjects: "Projetos entregues", statRating: "Avaliação média", statUptime: "Uptime dos servidores",
      servEyebrow: "O que eu construo", servTitle: "Do documento de design ao servidor no ar.",
      servSub: "Quatro frentes de trabalho. Cada uma com um projeto entregue que você pode abrir e conferir agora.",
      servProof: "Ver a prova",
      serv1Title: "Game design e narrativa", serv1Model: "Projeto fechado ou consultoria",
      serv1Promise: "Seu jogo sai do papel com regras que fecham e conteúdo que prende.",
      serv1Desc: "Documento de design, campanha, progressão, economia, diálogos e balanceamento. Entrego o GDD pronto para o time de produção executar sem adivinhação.",
      serv2Title: "Servidores e sistemas Minecraft", serv2Model: "Projeto fechado ou evolução contínua",
      serv2Promise: "Seu servidor aguenta o dia do lançamento.",
      serv2Desc: "Plugins, minigames, dungeons instanciadas, NPCs animados, cinematics e economia multi-servidor, sobre uma arquitetura dimensionada para centenas de jogadores simultâneos.",
      serv3Title: "Eventos ao vivo e infraestrutura", serv3Model: "Sob demanda, por evento",
      serv3Promise: "O evento acontece na hora marcada, sem queda no ar.",
      serv3Desc: "Dimensionamento para o pico, teste de carga antes da gravação, monitoramento durante o evento e plano de contingência. Já rodei com criador ao vivo e 350+ jogadores simultâneos.",
      serv4Title: "Software, IA e web", serv4Model: "Projeto fechado ou mensal",
      serv4Promise: "A parte chata roda sozinha, com resposta certa e rastreável.",
      serv4Desc: "Aplicações Java/Spring e Python, bots com RAG sobre a sua base de conhecimento, integrações com modelos de linguagem, sites e painéis administrativos.",
      projEyebrow: "Projetos em destaque", projTitle: "Trabalho recente.",
      filterAll: "Todos", filterMc: "Minecraft", filterGd: "Game Design", filterAi: "IA / Software",
      projDetails: "Ver detalhes", projDrop: "Arraste um screenshot", projVideo: "Espaço para vídeo", projEmpty: "Nenhum projeto nesta categoria ainda. Volte em breve.",
      aboutEyebrow: "Sobre mim", aboutTitle: "Quem está por trás do código.",
      aboutRole: "Software Engineer & Game Designer · Certificado pela CalArts · Sistemas de Informação, UFG",
      aboutLead: "Sou apaixonado por transformar ideias em realidade.",
      aboutBody: "Sou Software Engineer e Game Designer, certificado pela CalArts e cursando Sistemas de Informação na UFG. Engenharia de software, gestão de projetos, game design, escrita criativa e marketing raramente andam juntos, e é essa mistura que me deixa levar um projeto do escopo à entrega. Versátil, mas com uma especialidade clara: transformar o impossível em possível.",
      aboutHint: "passe o mouse",
      aboutFact1: "Certificado CalArts", aboutFact2: "Cursando UFG", aboutFact3: "Bilíngue (PT / EN)", aboutFact4: "Brasil",
      testiEyebrow: "Depoimentos", testiTitle: "O que dizem os clientes.", testiDrag: "Arraste para navegar",
      testiQ1: "Entregou o plugin antes do prazo e a comunidade adorou. Comunicação impecável do começo ao fim.", testiR1: "Dono · MineCraftBR Network",
      testiQ2: "Clean code, clear English and on-time delivery. Would hire Vitor again in a heartbeat.", testiR2: "CTO · Nordic Apps",
      procEyebrow: "Como eu trabalho", procTitle: "Sem surpresa no meio do caminho.",
      procSub: "Todo projeto segue o mesmo processo, do primeiro contato ao suporte depois da entrega.",
      procG1: "Resposta em até 24h", procG2: "Escopo e prazo por escrito", procG3: "Suporte após a entrega",
      proc1t: "Conversa", proc1m: "Dia 1", proc1d: "Você me conta a ideia. Eu faço as perguntas que definem o problema antes de qualquer linha de código.",
      proc2t: "Escopo e proposta", proc2m: "Até 3 dias", proc2d: "Você recebe escopo, prazo, valor e o que está fora do projeto, tudo por escrito, antes de fechar.",
      proc3t: "Desenvolvimento", proc3m: "Por marcos", proc3d: "Entregas parciais em marcos combinados. Você acompanha o progresso e ajusta o rumo no caminho, não no fim.",
      proc4t: "Entrega e suporte", proc4m: "Contínuo", proc4d: "Instalação, documentação e handoff para a sua equipe. Depois disso, suporte para ajustes e dúvidas.",
      contactEyebrow: "Bora construir algo", contactTitle: "Tem um projeto em mente?",
      contactSub: "Servidor de Minecraft, app, integração com IA? Me conta a ideia e eu retorno em até 24h.",
      formName: "Nome", formEmail: "E-mail", formMessage: "Mensagem",
      formNamePh: "Como posso te chamar?", formEmailPh: "voce@email.com", formMsgPh: "Me conta sobre o projeto: escopo, prazo, o que você imagina.",
      formSubmit: "Enviar mensagem", formSending: "Enviando", successTitle: "Mensagem enviada!", successText: "Obrigado pelo contato. Retorno em até 24h, normalmente bem antes disso.", successAgain: "Enviar outra mensagem",
      dcEyebrow: "Falha no envio",
      dcTitle: "O formulário não enviou.",
      dcText: "Parece que o sistema de e-mail falhou. Me chama no Discord, minha DM é aberta:",
      dcHandle: "icegames",
      dcAskTitle: "No recado, me conta:",
      askProject: "O que é o projeto e qual problema ele resolve",
      askTimeline: "Prazo que você tem em mente",
      askBudget: "Orçamento disponível",
      askScale: "Escala esperada: jogadores, usuários ou tamanho da equipe",
      dcCopy: "Copiar mensagem", dcClose: "Fechar",
      footerTagline: "Transformando o impossível em possível.",
      modalCta: "Quero algo assim",
      errName: "Como posso te chamar?", errEmail: "Confere o e-mail, parece que falta alguma coisa.", errMessage: "Conte um pouco mais (mínimo 10 caracteres).",
    },
    en: {
      navProjects: "Projects", navServices: "Services", navProcess: "How I work", navAbout: "About", navContact: "Contact", navCta: "Let's talk",
      heroAvailable: "Available for new projects",
      heroRole: "Software Engineer & Game Designer · CalArts certified",
      heroH1a: "Turning the impossible into the ", heroH1b: "possible",
      heroClients: "Worked with", heroClientFree: "+ logo",
      heroSub: "I'm Vitor Albert, a.k.a. IceGames. I design the game and build the engineering that keeps it standing: Minecraft servers, live events and AI-powered software that run with hundreds of current players.",
      heroCta1: "View projects", heroCta2: "Let's talk",
      statPlayers: "Players reached", statProjects: "Projects shipped", statRating: "Average rating", statUptime: "Server uptime",
      servEyebrow: "What I build", servTitle: "From the design document to the server going live.",
      servSub: "Four areas of work. Each one with a delivered project you can open and check right now.",
      servProof: "See the proof",
      serv1Title: "Game design and narrative", serv1Model: "Fixed project or consulting",
      serv1Promise: "Your game leaves the page with rules that hold and content that keeps people playing.",
      serv1Desc: "Design document, campaign, progression, economy, dialogue and balancing. I hand over a GDD the production team can execute without guesswork.",
      serv2Title: "Minecraft servers and systems", serv2Model: "Fixed project or ongoing work",
      serv2Promise: "Your server holds up on launch day.",
      serv2Desc: "Plugins, minigames, instanced dungeons, animated NPCs, cinematics and multi-server economies, on an architecture sized for hundreds of concurrent players.",
      serv3Title: "Live events and infrastructure", serv3Model: "On demand, per event",
      serv3Promise: "The event happens on schedule, with nothing going down on air.",
      serv3Desc: "Peak sizing, load testing before the shoot, monitoring during the event and a contingency plan. Already run live with a creator and 350+ concurrent players.",
      serv4Title: "Software, AI and web", serv4Model: "Fixed project or monthly",
      serv4Promise: "The tedious part runs itself, with answers that are correct and traceable.",
      serv4Desc: "Java/Spring and Python applications, bots with RAG over your knowledge base, language-model integrations, websites and admin panels.",
      projEyebrow: "Featured projects", projTitle: "Recent work.",
      filterAll: "All", filterMc: "Minecraft", filterGd: "Game Design", filterAi: "AI / Software",
      projDetails: "View details", projDrop: "Drop a screenshot", projVideo: "Video goes here", projEmpty: "No projects in this category yet. Check back soon.",
      aboutEyebrow: "About me", aboutTitle: "The person behind the code.",
      aboutRole: "Software Engineer & Game Designer · CalArts certified · Information Systems, UFG",
      aboutLead: "I'm passionate about turning ideas into reality.",
      aboutBody: "I'm a Software Engineer and Game Designer, CalArts certified and currently studying Information Systems at UFG. Software engineering, project management, game design, creative writing and marketing rarely come together, and that mix is what lets me carry a project from scope to delivery. Versatile, but with one clear specialty: turning the impossible into the possible.",
      aboutHint: "hover to flip",
      aboutFact1: "CalArts certified", aboutFact2: "Studying at UFG", aboutFact3: "Bilingual (PT / EN)", aboutFact4: "Based in Brazil",
      testiEyebrow: "Testimonials", testiTitle: "What clients say.", testiDrag: "Drag to explore",
      testiQ1: "Delivered the plugin ahead of schedule and the community loved it. Flawless communication from start to finish.", testiR1: "Owner · MineCraftBR Network",
      testiQ2: "Clean code, clear English and on-time delivery. Would hire Vitor again in a heartbeat.", testiR2: "CTO · Nordic Apps",
      procEyebrow: "How I work", procTitle: "No surprises along the way.",
      procSub: "Every project follows the same process, from first contact to support after delivery.",
      procG1: "Reply within 24h", procG2: "Scope and deadline in writing", procG3: "Support after delivery",
      proc1t: "Conversation", proc1m: "Day 1", proc1d: "You tell me the idea. I ask the questions that define the problem before a single line of code.",
      proc2t: "Scope and quote", proc2m: "Within 3 days", proc2d: "You get scope, timeline, price and what's out of scope, all in writing, before we start.",
      proc3t: "Development", proc3m: "By milestones", proc3d: "Partial deliveries at agreed milestones. You follow progress and adjust course along the way, not at the end.",
      proc4t: "Delivery and support", proc4m: "Ongoing", proc4d: "Setup, documentation and handoff to your team. After that, support for tweaks and questions.",
      contactEyebrow: "Let's build something", contactTitle: "Got a project in mind?",
      contactSub: "Minecraft server, app, AI integration? Tell me the idea and I'll get back within 24h.",
      formName: "Name", formEmail: "Email", formMessage: "Message",
      formNamePh: "What should I call you?", formEmailPh: "you@email.com", formMsgPh: "Tell me about the project: scope, timeline, what you have in mind.",
      formSubmit: "Send message", formSending: "Sending", successTitle: "Message sent!", successText: "Thanks for reaching out. I'll reply within 24h, usually much sooner.", successAgain: "Send another message",
      dcEyebrow: "Sending failed",
      dcTitle: "The form didn't send.",
      dcText: "Looks like the email system failed. Message me on Discord, my DMs are open:",
      dcHandle: "icegames",
      dcAskTitle: "In your message, tell me:",
      askProject: "What the project is and the problem it solves",
      askTimeline: "The timeline you have in mind",
      askBudget: "Budget available",
      askScale: "Expected scale: players, users or team size",
      dcCopy: "Copy message", dcClose: "Close",
      footerTagline: "Turning the impossible into the possible.",
      modalCta: "I want something like this",
      errName: "What should I call you?", errEmail: "Check the email, something seems off.", errMessage: "Tell me a bit more (at least 10 characters).",
    },
  },
};
